# This file is required by the the action 'https://github.com/actions/labeler'
# and used in the '.github/workflows/ci_cd_pr.yml' workflow

# -- Labels based on PR title ------------------------------------------------
'fix':
  - head-branch: ['fix']

'enhancement':
  - head-branch: ['feat']

# -- Documentation labels ----------------------------------------------------
'docs':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['doc/source/**/*.rst']
          - all-globs-to-all-files: ['!doc/source/examples.rst', '!doc/source/api/**/*.rst',
              '!doc/styles/**', '!doc/.vale.ini']

'docs:api':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['doc/source/api/**/*.rst']

'docs:examples':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['examples/**/*.py', 'doc/source/examples.rst']

## -- Other labels ------------------------------------------------------------
'style:code':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.pre-commit-config.yaml', 'doc/.vale.ini']

'docker':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['docker/**']

'ci':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.github/workflows/**']

'tests':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['tests/**']

# HACK: the following labels are declared with the only purpose of avoiding the
# GitHub labeler bot to remove those. This is a known issue reported in the
# official action/labeler repo https://github.com/actions/labeler/issues/763

'ci:skip':
  - all:
      - changed-files:
          - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']

'docs:skip':
  - all:
      - changed-files:
          - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']

'tests:skip':
  - all:
      - changed-files:
          - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']

'blocked':
  - all:
      - changed-files:
          - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']
